# Site settings
# Use David Brough credentials to moderate the entire site.
title: Materials Informatics Course Labs
email: david.brough.0416@gmail.com, ahmetcecen@gmail.com
description: >
  Lab Page for the GT Materials Informatics Course
# Using ``gh`` so the site.github is still available
gh:
  user: rcui9
  repo: Labs
  # Branch hosting Github pages
  branch: gh-pages
baseurl: "/Labs" # the subpath of your site, e.g. /blog/
url: "rcui9.github.io" # the base hostname & protocol for your site
# Last line in commenting command
disqus: davidbrough, ahmetcecen

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5
